### PR TITLE
Added AP-1 Page Template

### PR DESCRIPTION
**Pull request by LAACharlesBoardman**
Page template is in place.
Content will needs to be altered.

### CODE REVIEW

**Comment by LAACharlesBoardman** [comment]
Thanks Mark.  I'll get to cleaning this up.

**Comment by a5rar** [comment]
Hi Charles, 

Please re-base with master so you can take the latest changes..  This should be done before you check any branches in

**Comment by LAACharlesBoardman** [comment]
Thanks Asrar. I'll do that now before I make any further changes.

**Comment by mpw5** [comment]
Mostly good. There are some further changes that are needed but I'll approve now to allow progress and because I don't want to try and do too much in one PR: 

- you can go further with moving code out of index.html.erb into application.html.erb;
- there are a few errors being thrown by the app - check the output logged in the terminal while it's running to see them;
- the service name seems to have disappeared (not sure if that's deliberate?)

@LAACharlesBoardman If you're in tomorrow I'm happy to sit with you and go through it.

**Pull request merged**
